#!/usr/bin/env python3
"""Emit a Markdown table of every `Settings` field ↔ env alias (single source of truth).

Usage (from `backend/`):
  uv run python scripts/dump_settings_registry.py
  uv run python scripts/dump_settings_registry.py --tsv
  uv run python scripts/dump_settings_registry.py --secrets
"""

from __future__ import annotations

import argparse
import sys
from typing import Any, get_args, get_origin

from cognitive_os.core.config import Settings


def _type_str(annotation: Any) -> str:
    if annotation is None:
        return "Any"
    if isinstance(annotation, type):
        return annotation.__name__
    origin = get_origin(annotation)
    args = get_args(annotation)
    if origin is None:
        return str(annotation).replace("typing.", "")
    inner = ", ".join(_type_str(a) for a in args)
    return f"{getattr(origin, '__name__', str(origin))}[{inner}]"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--tsv",
        action="store_true",
        help="Print tab-separated python_attr, ENV_ALIAS, type",
    )
    parser.add_argument(
        "--secrets",
        action="store_true",
        help="List fields validated by reject_changeme_in_production (alias + Python name)",
    )
    parser.add_argument(
        "--out",
        type=str,
        metavar="PATH",
        help="Write Markdown table to PATH with stable header comment",
    )
    args = parser.parse_args()

    if args.secrets:
        print("| Python attribute | Reject `CHANGEME` in prod | Env alias |")
        print("|------------------|---------------------------|-----------|")
        for fname in sorted(Settings._production_secret_fields):
            finfo = Settings.model_fields.get(fname)
            alias = finfo.alias if finfo and finfo.alias else fname.upper()
            print(f"| `{fname}` | yes | `{alias}` |")
        return 0

    rows: list[tuple[str, str, str]] = []
    for py_name in sorted(Settings.model_fields):
        finfo = Settings.model_fields[py_name]
        if py_name.startswith("_"):
            continue
        alias = finfo.alias
        if not alias:
            continue
        ann = finfo.annotation
        rows.append((py_name, str(alias), _type_str(ann)))

    if args.tsv:
        for py_name, alias, typ in rows:
            print(f"{py_name}\t{alias}\t{typ}")
        return 0

    table_lines: list[str] = [
        "| `Settings` attribute | Environment variable (`alias`) | Type |",
        "|----------------------|----------------------------------|------|",
    ]
    for py_name, alias, typ in rows:
        table_lines.append(f"| `{py_name}` | `{alias}` | {_md_escape(typ)} |")
    table_text = "\n".join(table_lines) + "\n"

    if args.out:
        header = (
            "<!-- Generated by `backend/scripts/dump_settings_registry.py`. "
            "Do not edit by hand. -->\n\n"
        )
        with open(args.out, "w", encoding="utf-8") as fh:
            fh.write(header + table_text)
        return 0

    sys.stdout.write(table_text)
    return 0


def _md_escape(s: str) -> str:
    return s.replace("|", "\\|").replace("\n", " ")


if __name__ == "__main__":
    sys.exit(main())
