"""F8 end-to-end: a build that actually writes files and is packaged.

This exercises the full director → adapter → workspace → tar.gz path with
a fake adapter that writes real files into the workspace (simulating what
a real coding CLI would do). It proves the artifact packaging and the
manifest are correct without spending any external tokens.
"""

from __future__ import annotations

import tarfile
from contextlib import asynccontextmanager
from datetime import UTC, datetime
from pathlib import Path
from uuid import UUID, uuid4

import pytest

import cognitive_os.code_director.service as svc_module
from cognitive_os.code_director.adapters.base import CodingAgentAdapter
from cognitive_os.code_director.director import CodeDirector
from cognitive_os.code_director.schemas import (
    AdapterPreference,
    AgentSession,
    CodeBuildRequest,
    StepResult,
)
from cognitive_os.code_director.service import CodeDirectorService
from cognitive_os.core.config import Settings
from cognitive_os.db.models import Job


class _FileWritingAdapter(CodingAgentAdapter):
    """Fake adapter that writes a real file per subtask into the workspace."""

    name = "fake"

    def is_available(self) -> bool:
        return True

    def start_session(
        self, *, workspace: Path, objective: str, model: str | None = None
    ) -> AgentSession:
        del objective, model
        return AgentSession(
            session_id=str(uuid4()),
            adapter="fake",
            workspace=str(workspace),
            state={"n": 0},
        )

    def send_prompt(
        self, session: AgentSession, prompt: str, *, timeout_seconds: float = 600.0
    ) -> StepResult:
        del timeout_seconds
        ws = Path(session.workspace)
        ws.mkdir(parents=True, exist_ok=True)
        n = int(session.state.get("n", 0)) + 1
        session.state["n"] = n
        target = ws / f"generated_{n}.py"
        target.write_text(f"# generated by fake adapter, prompt len={len(prompt)}\n")
        return StepResult(success=True, stdout=f"wrote {target.name}", files_touched=[target.name])

    def cleanup(self, session: AgentSession) -> None:
        del session


class _Store:
    def __init__(self) -> None:
        self.objects: dict[UUID, object] = {}

    @asynccontextmanager
    async def scope(self):
        store = self

        class _S:
            def add(self, obj: object) -> None:
                oid = getattr(obj, "id", None)
                if oid is None:
                    obj.id = uuid4()
                    oid = obj.id
                if getattr(obj, "created_at", None) is None:
                    obj.created_at = datetime.now(UTC)
                if getattr(obj, "updated_at", None) is None:
                    obj.updated_at = datetime.now(UTC)
                store.objects[oid] = obj

            async def flush(self) -> None:
                return None

            async def get(self, model: type[object], oid: UUID) -> object | None:
                obj = store.objects.get(oid)
                return obj if isinstance(obj, model) else None

        yield _S()


@pytest.mark.asyncio
async def test_full_build_writes_files_and_packages_targz(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    store = _Store()
    monkeypatch.setattr(svc_module, "session_scope", store.scope)

    cfg = Settings(
        local_storage_dir=str(tmp_path / "storage"),
        document_output_root=tmp_path / "out",
    )
    director = CodeDirector(
        adapters={"fake": _FileWritingAdapter()},
        local_storage_dir=tmp_path / "storage",
    )
    service = CodeDirectorService(cfg, director=director, allow_fake_adapter=True)

    request = CodeBuildRequest(
        objective="Build a tiny CLI calculator with add/sub and tests" + " " * 40,
        adapter_preference=AdapterPreference(default_adapter="fake"),
    )

    job_id, _approval_id, plan = await service.create_build(request, requested_by="op-1")
    assert len(plan.subtasks) >= 3

    # Simulate the approval being accepted: the worker calls run_build.
    result = await service.run_build(job_id)

    assert result.status == "completed"
    assert result.artifact_path is not None
    archive = Path(result.artifact_path)
    assert archive.is_file()
    assert archive.suffix == ".gz"

    # The tar.gz contains the files the adapter wrote plus the manifest.
    with tarfile.open(archive, "r:gz") as tar:
        names = tar.getnames()
    joined = "\n".join(names)
    assert "generated_1.py" in joined
    assert "_codedirector_manifest.json" in joined

    # The job flipped to a terminal state.
    job = store.objects[job_id]
    assert isinstance(job, Job)
    assert job.status == "completed"


@pytest.mark.asyncio
async def test_full_build_budget_partial_still_packages(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """A budget-capped run stops as `partial` but still delivers what it built."""
    store = _Store()
    monkeypatch.setattr(svc_module, "session_scope", store.scope)

    cfg = Settings(
        local_storage_dir=str(tmp_path / "storage"),
        document_output_root=tmp_path / "out",
    )
    director = CodeDirector(
        adapters={"fake": _FileWritingAdapter()},
        local_storage_dir=tmp_path / "storage",
    )
    service = CodeDirectorService(cfg, director=director, allow_fake_adapter=True)

    request = CodeBuildRequest(
        objective="Build something with several steps" + " " * 60,
        adapter_preference=AdapterPreference(default_adapter="fake"),
        budget={"max_total_llm_calls": 1, "max_calls_per_subtask": 1},
    )
    job_id, _a, _p = await service.create_build(request, requested_by="op-1")
    result = await service.run_build(job_id)

    assert result.status == "partial"
    assert result.artifact_path is not None
    assert Path(result.artifact_path).is_file()
